interface ReportPrintOptions {
  title: string;
  storeName?: string;
  dateRange?: string;
  content: string;
  orientation?: 'portrait' | 'landscape';
  subtitle?: string;
}

export function printReport(options: ReportPrintOptions): void {
  const {
    title,
    storeName = 'AByte ERP',
    dateRange,
    content,
    orientation = 'portrait',
    subtitle,
  } = options;

  const printWindow = window.open('', '_blank', 'width=900,height=700');
  if (!printWindow) {
    alert('Please allow popups for printing');
    return;
  }

  const html = `<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <meta charset="UTF-8">
  <style>
    @page {
      size: A4 ${orientation};
      margin: 15mm;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      color: #1a1a1a;
      background: white;
      padding: 20px;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    .report-header {
      text-align: center;
      padding-bottom: 15px;
      border-bottom: 2px solid #1a1a1a;
      margin-bottom: 20px;
    }
    .store-name {
      font-size: 22px;
      font-weight: 700;
      letter-spacing: 1px;
    }
    .report-title {
      font-size: 18px;
      font-weight: 600;
      margin-top: 8px;
      text-transform: uppercase;
      letter-spacing: 2px;
    }
    .report-subtitle {
      font-size: 13px;
      color: #555;
      margin-top: 4px;
    }
    .date-range {
      font-size: 12px;
      color: #666;
      margin-top: 6px;
    }
    .print-date {
      font-size: 11px;
      color: #888;
      margin-top: 4px;
    }
    .report-content {
      margin-top: 10px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 15px;
      font-size: 12px;
    }
    th {
      background-color: #f3f4f6;
      font-weight: 600;
      text-transform: uppercase;
      font-size: 11px;
      letter-spacing: 0.5px;
      color: #374151;
      padding: 8px 10px;
      border: 1px solid #d1d5db;
      text-align: left;
    }
    td {
      padding: 6px 10px;
      border: 1px solid #e5e7eb;
      color: #1f2937;
    }
    tr:nth-child(even) {
      background-color: #f9fafb;
    }
    .text-right { text-align: right; }
    .text-center { text-align: center; }
    .font-bold { font-weight: 700; }
    .font-semibold { font-weight: 600; }
    .text-lg { font-size: 14px; }
    .text-sm { font-size: 11px; }
    .text-green { color: #059669; }
    .text-red { color: #dc2626; }
    .summary-row {
      background-color: #f0fdf4 !important;
      font-weight: 700;
    }
    .summary-row td {
      border-top: 2px solid #1a1a1a;
      padding: 10px;
    }
    .section-title {
      font-size: 14px;
      font-weight: 700;
      margin: 20px 0 8px;
      padding-bottom: 4px;
      border-bottom: 1px solid #d1d5db;
      color: #111827;
    }
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 12px;
      margin-bottom: 20px;
    }
    .stat-card {
      border: 1px solid #d1d5db;
      border-radius: 6px;
      padding: 12px;
      text-align: center;
    }
    .stat-label {
      font-size: 11px;
      color: #6b7280;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .stat-value {
      font-size: 18px;
      font-weight: 700;
      color: #111827;
      margin-top: 4px;
    }
    .report-footer {
      margin-top: 30px;
      padding-top: 10px;
      border-top: 1px solid #d1d5db;
      text-align: center;
      font-size: 10px;
      color: #9ca3af;
    }
    @media print {
      body { padding: 0; }
      .no-print { display: none !important; }
    }
  </style>
</head>
<body>
  <div class="report-header">
    <div class="store-name">${escapeHtml(storeName)}</div>
    <div class="report-title">${escapeHtml(title)}</div>
    ${subtitle ? `<div class="report-subtitle">${escapeHtml(subtitle)}</div>` : ''}
    ${dateRange ? `<div class="date-range">${escapeHtml(dateRange)}</div>` : ''}
    <div class="print-date">Printed: ${new Date().toLocaleString()}</div>
  </div>
  <div class="report-content">
    ${content}
  </div>
  <div class="report-footer">
    Generated by AByte ERP &mdash; ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`;

  printWindow.document.write(html);
  printWindow.document.close();

  setTimeout(() => {
    printWindow.focus();
    printWindow.print();
  }, 600);
}

function escapeHtml(str: string): string {
  const div = document.createElement('div');
  div.appendChild(document.createTextNode(str));
  return div.innerHTML;
}

// Helper to build an HTML table from data arrays
export function buildTable(
  headers: string[],
  rows: string[][],
  options?: {
    alignRight?: number[];
    summaryRow?: string[];
    caption?: string;
  }
): string {
  const alignRight = new Set(options?.alignRight || []);

  let html = '';
  if (options?.caption) {
    html += `<div class="section-title">${escapeHtml(options.caption)}</div>`;
  }
  html += '<table><thead><tr>';
  headers.forEach((h, i) => {
    html += `<th${alignRight.has(i) ? ' class="text-right"' : ''}>${escapeHtml(h)}</th>`;
  });
  html += '</tr></thead><tbody>';
  rows.forEach(row => {
    html += '<tr>';
    row.forEach((cell, i) => {
      html += `<td${alignRight.has(i) ? ' class="text-right"' : ''}>${cell}</td>`;
    });
    html += '</tr>';
  });
  if (options?.summaryRow) {
    html += '<tr class="summary-row">';
    options.summaryRow.forEach((cell, i) => {
      html += `<td${alignRight.has(i) ? ' class="text-right"' : ''}>${cell}</td>`;
    });
    html += '</tr>';
  }
  html += '</tbody></table>';
  return html;
}

// Helper to build stats cards HTML
export function buildStatsCards(stats: { label: string; value: string }[]): string {
  let html = '<div class="stats-grid">';
  stats.forEach(s => {
    html += `<div class="stat-card"><div class="stat-label">${escapeHtml(s.label)}</div><div class="stat-value">${escapeHtml(s.value)}</div></div>`;
  });
  html += '</div>';
  return html;
}
